
syntax = "proto3";
option go_package = "prosessor/proto";

package calculate;

service Calculate {
  rpc Calculate (CalculateRequest) returns (CalculateReply) {}
}

message CalculateRequest {
  string symbol = 1;
  double currentPrice = 2;
  double boughtPrice = 3;
  double walletBaseBalance = 4;
  double walletQuoteBalance = 5;
  repeated double priceHistories = 6 [packed=true];
  repeated double purchasePowers = 7 [packed=true];
  repeated double sellPowers = 8 [packed=true];
}

message CalculateReply {
  bool shouldBuy = 1;
  bool shouldSell = 2;
}
