export const {
  PORT = 3000,
  APP__API_KEY = '',
  APP__NAME = '',
  APP__DOCS_DESCRIPTION = '',
  APP__DOCS_SERVER_URLS = '',
  MONGODB__DATABASE = '',
  MONGODB__HOST = 'localhost:27017',
  MONGODB__URI = 'mongodb://localhost:27017',
  JWT__PRIVATE_KEY = '',
  JWT__PUBLIC_KEY = '',
  USER_GROUPS__ENCRYPTION_KEY = '',
} = process.env;
