version: '3.9'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: icd_internal_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./database/mysql/:/var/lib/mysql
    networks:
      - default
      
networks:
  default:
    driver: bridge
 