# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.1'

services:
  postgresql:
    image: postgres:16-alpine
    container_name: postgres_server
    ports:
      - '5432:5432'
    volumes:
      - ./database/postgres/:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    networks:
      - postgres_net

  p_admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - postgres_net

networks:
  postgres_net:
    driver: bridge
